apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vneu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-vneu@sha256:dc278ae9e7d641d7c12a0f5a23c74b7b7e9596ee2cef7e0a0a0ad164e4af63c9
        name: my-nodejs
        resources: {}
status: {}
